// usersInsert.js
// use sporturedb;

db.users.insertMany([
  {
    "name": "Radha Raman",
    "email": "radha@example.com",
    "password": "123456",
    "favSports": ["Badminton", "Football"],
    "skillLevel": "Intermediate",
    "rating": 4,
    "gamesPlayed": 12,
    "eventsHosted": 3,
    "photoURL": "RadhaKrishna.jpg",
    "memberSince": "Jan 2024",
    "city": "Bengaluru",
    "bio": "Sports enthusiast who loves competitive badminton and weekend football matches!"
  },
  {
    "name": "Ahana Sharma",
    "email": "ahana@sporture.com",
    "password": "123456",
    "favSports": ["Tennis", "Badminton"],
    "skillLevel": "Intermediate",
    "rating": 4.5,
    "gamesPlayed": 20,
    "eventsHosted": 5,
    "photoURL": "ahana.jpg",
    "memberSince": "Feb 2024",
    "city": "Mumbai",
    "bio": "Loves organizing community tennis matches and mentoring new players."
  },
  {
    "name": "Srivani Rao",
    "email": "srivani@sporture.com",
    "password": "123456",
    "favSports": ["Football", "Cricket"],
    "skillLevel": "Advanced",
    "rating": 4.2,
    "gamesPlayed": 25,
    "eventsHosted": 7,
    "photoURL": "srivani.jpg",
    "memberSince": "Mar 2024",
    "city": "Hyderabad",
    "bio": "Passionate about competitive football and local league organization."
  },
  {
    "name": "Shri",
    "email": "shri@sporture.com",
    "password": "123456",
    "favSports": ["Basketball", "Tennis"],
    "skillLevel": "Intermediate",
    "rating": 4.3,
    "gamesPlayed": 15,
    "eventsHosted": 2,
    "photoURL": "shri.jpg",
    "memberSince": "Apr 2024",
    "city": "Chennai",
    "bio": "Enjoys weekend basketball tournaments and helping manage event logistics."
  },
  {
    "name": "Arjun Patel",
    "email": "arjun@sporture.com",
    "password": "123456",
    "favSports": ["Football"],
    "skillLevel": "Beginner",
    "rating": 3.8,
    "gamesPlayed": 8,
    "eventsHosted": 1,
    "photoURL": "arjun.jpg",
    "memberSince": "May 2024",
    "city": "Ahmedabad",
    "bio": "Football fan starting his sports journey with local club matches."
  },
  {
    "name": "Meera Iyer",
    "email": "meera@sporture.com",
    "password": "123456",
    "favSports": ["Cricket", "Badminton"],
    "skillLevel": "Professional",
    "rating": 4.9,
    "gamesPlayed": 45,
    "eventsHosted": 10,
    "photoURL": "meera.jpg",
    "memberSince": "Jan 2023",
    "city": "Delhi",
    "bio": "Professional cricket coach and weekend badminton doubles champion."
  },
  {
    "name": "Rohit Sen",
    "email": "rohit@sporture.com",
    "password": "123456",
    "favSports": ["Football", "Basketball"],
    "skillLevel": "Advanced",
    "rating": 4.4,
    "gamesPlayed": 30,
    "eventsHosted": 6,
    "photoURL": "rohit.jpg",
    "memberSince": "Jun 2024",
    "city": "Kolkata",
    "bio": "Multi-sport athlete passionate about community sports development."
  },
  {
    "name": "Kavya Nair",
    "email": "kavya@sporture.com",
    "password": "123456",
    "favSports": ["Tennis"],
    "skillLevel": "Intermediate",
    "rating": 4.1,
    "gamesPlayed": 12,
    "eventsHosted": 3,
    "photoURL": "kavya.jpg",
    "memberSince": "Feb 2024",
    "city": "Pune",
    "bio": "Active tennis player promoting women's participation in local leagues."
  },
  {
    "name": "Vikram Desai",
    "email": "vikram@sporture.com",
    "password": "123456",
    "favSports": ["Cricket"],
    "skillLevel": "Professional",
    "rating": 4.7,
    "gamesPlayed": 40,
    "eventsHosted": 9,
    "photoURL": "vikram.jpg",
    "memberSince": "Nov 2023",
    "city": "Surat",
    "bio": "Professional bowler and mentor for upcoming cricket players."
  },
  {
    "name": "Ananya Gupta",
    "email": "ananya@sporture.com",
    "password": "123456",
    "favSports": ["Badminton", "Football"],
    "skillLevel": "Beginner",
    "rating": 3.9,
    "gamesPlayed": 6,
    "eventsHosted": 0,
    "photoURL": "ananya.jpg",
    "memberSince": "Jul 2024",
    "city": "Lucknow",
    "bio": "College student exploring new sports with friends."
  }
]);
